"""updated db

Revision ID: c28bd4c20e5d
Revises: c68af6c008d6
Create Date: 2025-10-28 13:14:20.040605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28bd4c20e5d'
down_revision = 'c68af6c008d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('court_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('opposing_party', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('opposing_counsel', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_column('opposing_counsel')
        batch_op.drop_column('opposing_party')
        batch_op.drop_column('court_name')
        batch_op.drop_column('case_number')

    # ### end Alembic commands ###
